[phases.setup]
nixPkgs = ["python313", "postgresql_16.dev", "gcc", "nodejs_20"]

[phases.install]
cmds = [
    "npm install",
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "mv manage.py manage.py.bak || true",
    "npm run build:all",
    "mv manage.py.bak manage.py || true"
]

[start]
cmd = ". /opt/venv/bin/activate && bash scripts/railway-start.sh"
